[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "profeyelar"
version = "1.0.4"
description = "UI-based tool for project end-to-end profiling"
dependencies = [
    "setuptools<85",
    "requests<3",
    "memray<2"
]
readme = "README.md"
authors = [
    {name = "puzzleYOU GmbH"}
]
license = "MIT"
classifiers = []
